### ISSUE TITLE
non-lazy gettext calls at import time

### ISSUE THREAD

**Issue by michaelkuty** [jamesturk/django-markupfield#30]
Django==1.7.7

For example, ugettext() uses the app registry to look up translation catalogs in applications. To translate at import time, you need ugettext_lazy() instead. (Using ugettext() would be a bug, because the translation would happen at import time, rather than at each request depending on the active language.)

**Comment by jamesturk** [comment]
thanks for this, two quick questions-

1) is there a reason to not just replace the calls w/ ugettext_lazy instead of doing the aliased import, just thinking it might be clearer
2) do you know if there's a decent way to write a test that fails without this, it might not be possible given how the app loading stuff interfaces with testing

**Comment by michaelkuty** [comment]
1) refactored to django convention
2) im not expert for testing django but i thing, this is hard to reproduce in test case i create sample of import in settings file which makes error with non lazy call, but with lazy translation is everything OK
i don't know if it's right test case

**Comment by jamesturk** [comment]
thanks!
